### ISSUE TITLE
none

### ISSUE THREAD

**Issue by helloiamchen** [mayuefine/c_AMPs-prediction#11]
no more questions

**Comment by helloiamchen** [comment]
In addition, we found one more error when predicting AMPs using LSTM model under Attention environment. @mayuefine  HERE IS THE REPORT.
For LSTM Prediction
h5py=2.9.0
Keras=2.2.4
numpy=1.16.2
tensorflow-gpu=1.14.0
Python=3.6.9


Using TensorFlow backend.
WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:131: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

2023-07-25 07:18:44.863351: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2023-07-25 07:18:44.897691: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2023-07-25 07:18:45.807231: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560131573550 executing computations on platform CUDA. Devices:
2023-07-25 07:18:45.807314: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla V100-PCIE-32GB, Compute Capability 7.0
2023-07-25 07:18:45.807345: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): Tesla V100-PCIE-32GB, Compute Capability 7.0
2023-07-25 07:18:45.807373: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (2): Tesla V100-PCIE-32GB, Compute Capability 7.0
2023-07-25 07:18:45.807400: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (3): Tesla V100-PCIE-32GB, Compute Capability 7.0
2023-07-25 07:18:45.933141: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2023-07-25 07:18:45.941160: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560131855fc0 executing computations on platform Host. Devices:
2023-07-25 07:18:45.941220: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2023-07-25 07:18:45.968823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:18:00.0
2023-07-25 07:18:45.970195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2023-07-25 07:18:45.971326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:86:00.0
2023-07-25 07:18:45.972694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:af:00.0
2023-07-25 07:18:45.972896: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.972988: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.973067: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.973144: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.973223: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.973297: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.973376: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2023-07-25 07:18:45.973391: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2023-07-25 07:18:45.973451: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-07-25 07:18:45.973468: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 2 3 
2023-07-25 07:18:45.973482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y Y Y 
2023-07-25 07:18:45.973495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N Y Y 
2023-07-25 07:18:45.973509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 2:   Y Y N Y 
2023-07-25 07:18:45.973521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 3:   Y Y Y N 
2023-07-25 07:18:46.556089: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "prediction_lstm.py", line 9, in <module>
    x = loadtxt(argv[1], delimiter=",")
  File "/home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1134, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/data/chenhao/anaconda2/envs/Attention/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1058, in read_data
    % line_num)
ValueError: Wrong number of columns at line 143

**Comment by helloiamchen** [comment]
Lastly, the BERT prediction also failed due to the following reason:
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Traceback (most recent call last):
  File "prediction_bert.py", line 11, in <module>
    import pandas as pd
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/core/computation/ops.py", line 17, in <module>
    from pandas.core.computation.scope import _DEFAULT_GLOBALS
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/core/computation/scope.py", line 17, in <module>
    from pandas.compat.chainmap import DeepChainMap
  File "/home/data/chenhao/anaconda2/envs/BERT/lib/python3.6/site-packages/pandas/compat/chainmap.py", line 1, in <module>
    from typing import ChainMap, MutableMapping, TypeVar, cast
ImportError: cannot import name 'ChainMap'


For BERT Prediction
bert-sklearn=0.2.0
numpy=1.18.1
pandas=1.0.2
scikit-learn=0.22.1
tensorflow=1.14.0
Python=3.6
